unicsmcr/hs_hub

back-end/package-lock.json, back-end/src/util/cache/abstract-classes/cacheCollection.ts, back-end/test/unit/util/cache/models/collections/usersCacheCollection.test.ts
Implemented a method getElements in CacheCollection to return all elements in the collection. #17
=> Cache (getElements)

back-end/src/util/hardwareLibrary/hardwareItemValidation.ts
If a person tries to take out an item after a reservation has expired, the reservation is deleted from the hardware library and the hardware item table (reservation count) is updated to reflect the deletion
=> Delete reservation after expiry

src/util/announcement/oneSignalAnnouncement.ts
I missed this code when before the pull request was merged.
=> Remove old debug code from push notifications

src/util/errorHandling/errorHandler.ts, src/views/pages/404.ejs
For issue #83 
Made a custom 404 page instead of returning a JSON response
=> Updated the 404 page

src/util/team/teamValidation.ts, test/unit/util/team/teamValidation.test.ts
For issue #86 
Add team validation unit tests to ensure that the team system works as we expect. Still need to add some end-2-end tests but this can be done later.
=> Add team validation tests

src/util/user/passportLocalStrategy.ts, src/util/user/userValidation.ts
For issue #93 
The main issue was that user was being added to the database before we set the users team.
=> Sync applications teams to the hub

src/util/hardwareLibrary/hardwareItemValidation.ts
There's a type error which prevents the app running on the production deployment.
=> Fix validation error

src/public/css/cookieDisclaimer.css, src/public/css/navbar.css, src/public/js/cookieDisclaimer.js, src/views/pages/login.ejs, src/views/partials/cookieDisclaimer.ejs, src/views/partials/footer.ejs, src/views/partials/navbar.ejs
For issue #84 
Implemented a cookies disclaimer, fixed an issue with the in-app notifications appearing under the sidebar and updated a few links to other websites.
=> Implement cookie disclaimer

src/app.ts, src/util/achievements/localAchievements.ts
FIx the id of the tresure hunt achievement and an issue with the link for one of the achievements
=> Fix achievements

src/util/achievements/localAchievements.ts
Changed max progress from 3 to 2 since we only have 2 workshops
=> Update workshops achievement

.dockerignore, .travis.yml, CHANGELOG.md, Dockerfile, README.md, docker-compose.yml, launch_production.sh
For issue #111 
This pull request adds docker support, it can be used for getting started with development quickly. The docker compose file creates two containers and connect them together
- One for the hub running a nodejs-alpine image
- The other for a mysql database
Once the database is up, you can connect to it using MySQL database admin software like MySQL Workbench.
=> Docker support

.gitignore, package-lock.json
See for more details: https://npmjs.com/advisories/1013
=> Update pkg versions to resolve npm advisory 1013

src/app.ts, src/server.ts, test/unit/app.test.ts, test/unit/util/achievements/achievement.test.ts, test/unit/util/achievements/localAchievementsRepository.test.ts, test/util/testUtils.ts
This PR refactors buildApp to use promises instead of callbacks (same as https://github.com/unicsmcr/hs_application/commit/2ae0e97a8edb373d13ca43d443dbc21edb550a81), and also fixes some of the util tests which just had minor issues preventing them from running.
=> refactor: promisify buildApp, fix util tests

package-lock.json, package.json, src/controllers/teamController.ts, src/services/teams/teamService.ts, src/util/hs_auth.ts, test/unit/services/teamService.test.ts, test/unit/services/userService.test.ts
This PR integrates the auth client and replaces the code that interacted with the Auth API directly.
=> refactor: integrate @unicsmcr/hs_auth_client

.env.example, src/controllers/userController.ts, src/public/js/dashboard.js, src/routes/userRouter.ts, src/views/pages/dashboard.ejs
Adds a Twitch stream for the greatunihack channel. Stolen from the `sh2020` branch.
=> feat: Add Twitch stream to dashboard

gulpfile.js
Updates the gulpfile to include `.ico` files when building the dist directory
=> feat: Add .ico img files to gulpfile

gulpfile.js
Fixes a syntax error in the gulpfile
=> fix: gulpfile

package-lock.json, src/controllers/achievementsController.ts, src/routes/achievementsRouter.ts, src/util/auth/hs_auth.ts
Implements an operation to award an achievement to a user via an API call.
API reference for the new operation: https://documenter.getpostman.com/view/2489646/T1DjjKP6?version=latest#da53bf35-46d9-468d-b59a-f061b0c623e2
=> feat: Implement completeAchievement operation for API call use case

src/controllers/userController.ts, src/db/entity/userContactDetails.ts, src/public/js/dashboard.js, src/views/pages/dashboard.ejs
Updates the check-in form to include:
- Option to select dinner payment preference
- Option to not show the user's city
=> feat: Complete check-in form

src/db/entity/achievementProgress.ts
There was an issue where multiple users couldn't have the same achievement
=> fix: AchievementProgress schema
